-- MySQL Script generated by MySQL Workbench
-- Sam 17 Mär 2018 18:58:16 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cthulhu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cthulhu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cthulhu` DEFAULT CHARACTER SET utf8 ;
USE `cthulhu` ;

-- -----------------------------------------------------
-- Table `cthulhu`.`user_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cthulhu`.`user_information` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(25) NULL,
  `lname` VARCHAR(25) NULL,
  `photo` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `lat` FLOAT NULL,
  `type` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cthulhu`.`user_connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cthulhu`.`user_connection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(60) NULL,
  `user_hope_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_hope_id`),
  INDEX `fk_user_information_user_hope_idx` (`user_hope_id` ASC),
  CONSTRAINT `fk_user_information_user_hope`
    FOREIGN KEY (`user_hope_id`)
    REFERENCES `cthulhu`.`user_information` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cthulhu`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cthulhu`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cthulhu`.`themes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cthulhu`.`themes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `theme` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cthulhu`.`livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cthulhu`.`livre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `collection` VARCHAR(45) NULL,
  `éditions` VARCHAR(45) NULL,
  `authors_id` INT NOT NULL,
  `themes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `authors_id`, `themes_id`),
  INDEX `fk_livre_authors1_idx` (`authors_id` ASC),
  INDEX `fk_livre_themes1_idx` (`themes_id` ASC),
  CONSTRAINT `fk_livre_authors1`
    FOREIGN KEY (`authors_id`)
    REFERENCES `cthulhu`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_themes1`
    FOREIGN KEY (`themes_id`)
    REFERENCES `cthulhu`.`themes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cthulhu`.`hope/strength`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cthulhu`.`hope/strength` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hope/strength` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cthulhu`.`user_information_has_hope/strength`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cthulhu`.`user_information_has_hope/strength` (
  `user_information_id` INT NOT NULL,
  `hope/strength_id` INT NOT NULL,
  PRIMARY KEY (`user_information_id`, `hope/strength_id`),
  INDEX `fk_user_information_has_hope/strength_hope/strength1_idx` (`hope/strength_id` ASC),
  INDEX `fk_user_information_has_hope/strength_user_information1_idx` (`user_information_id` ASC),
  CONSTRAINT `fk_user_information_has_hope/strength_user_information1`
    FOREIGN KEY (`user_information_id`)
    REFERENCES `cthulhu`.`user_information` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_information_has_hope/strength_hope/strength1`
    FOREIGN KEY (`hope/strength_id`)
    REFERENCES `cthulhu`.`hope/strength` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cthulhu`.`livre_has_hope/strength`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cthulhu`.`livre_has_hope/strength` (
  `livre_id` INT NOT NULL,
  `livre_authors_id` INT NOT NULL,
  `livre_themes_id` INT NOT NULL,
  `hope/strength_id` INT NOT NULL,
  PRIMARY KEY (`livre_id`, `livre_authors_id`, `livre_themes_id`, `hope/strength_id`),
  INDEX `fk_livre_has_hope/strength_hope/strength1_idx` (`hope/strength_id` ASC),
  INDEX `fk_livre_has_hope/strength_livre1_idx` (`livre_id` ASC, `livre_authors_id` ASC, `livre_themes_id` ASC),
  CONSTRAINT `fk_livre_has_hope/strength_livre1`
    FOREIGN KEY (`livre_id` , `livre_authors_id` , `livre_themes_id`)
    REFERENCES `cthulhu`.`livre` (`id` , `authors_id` , `themes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_has_hope/strength_hope/strength1`
    FOREIGN KEY (`hope/strength_id`)
    REFERENCES `cthulhu`.`hope/strength` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

